This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/alberto/leyes y reglamentos/Trabajo_Final_de_Grado/2014/plantillas_latex/tfg/tfg.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file tfg.acn....done (18 entries accepted, 0 rejected).
Sorting entries....done (81 comparisons).
Generating output file tfg.acr....done (15 lines written, 0 warnings).
Output written in tfg.acr.
Transcript written in tfg.alg.
